package com.walgreens.pznoffer.sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SamplePojo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean superBool;
   private java.lang.Boolean subBool;

   private java.lang.Boolean thirdBool;

   public SamplePojo()
   {
   }

   public java.lang.Boolean getSuperBool()
   {
      return this.superBool;
   }

   public void setSuperBool(java.lang.Boolean superBool)
   {
      this.superBool = superBool;
   }

   public java.lang.Boolean getSubBool()
   {
      return this.subBool;
   }

   public void setSubBool(java.lang.Boolean subBool)
   {
      this.subBool = subBool;
   }

   public java.lang.Boolean getThirdBool()
   {
      return this.thirdBool;
   }

   public void setThirdBool(java.lang.Boolean thirdBool)
   {
      this.thirdBool = thirdBool;
   }

   public SamplePojo(java.lang.Boolean superBool, java.lang.Boolean subBool,
         java.lang.Boolean thirdBool)
   {
      this.superBool = superBool;
      this.subBool = subBool;
      this.thirdBool = thirdBool;
   }

}