package com.walgreens.pznoffer.sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SampleRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<com.walgreens.pznoffer.sample.SamplePojo> offerList;

   public SampleRequest()
   {
   }

   public java.util.List<com.walgreens.pznoffer.sample.SamplePojo> getOfferList()
   {
      return this.offerList;
   }

   public void setOfferList(
         java.util.List<com.walgreens.pznoffer.sample.SamplePojo> offerList)
   {
      this.offerList = offerList;
   }

   public SampleRequest(
         java.util.List<com.walgreens.pznoffer.sample.SamplePojo> offerList)
   {
      this.offerList = offerList;
   }

}